# Railway 项目配置
# 使用 Nixpacks 自动识别 Python 并安装 requirements.txt
[build]
builder = "nixpacks"

# 部署与服务配置
[[services]]
name = "okx-momentum-bot"
start = "python -u main.py"
restartPolicy = "always"

# 默认环境变量（可被 Railway Variables 面板覆盖）
# 机密不要写在这里，OKX_API_KEY/OKX_API_SECRET/OKX_API_PASSPHRASE 请在 Railway Variables 设置
[services.env]
# 动能脚本相关
MAIN_LOOP_INTERVAL = "10"
ATR_PERIOD = "14"
BODY_RATIO_THRESHOLD = "0.6"
CONFIRM_CANDLES = "2"
MIN_ORDER_USDT = "1"

# 保护参数
EXTREME_VOLATILITY_THRESHOLD = "0.05"
MIN_SL_DISTANCE_PCT = "0.005"
LIQUIDATION_BUFFER_PCT = "0.15"

# 运行环境
SANDBOX = "false"
LOG_LEVEL = "INFO"